"""fix updated_at nullable

Revision ID: 2075e0b7dfe5
Revises: c1e708115dd4
Create Date: 2026-03-02 12:36:47.271988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2075e0b7dfe5'
down_revision: Union[str, Sequence[str], None] = 'c1e708115dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columns', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('columns', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('columns', 'updated_at')
    op.drop_column('columns', 'created_at')
    # ### end Alembic commands ###
